#+title: About
#+filetags: about

My name is Ayush Kanodia. I'm a PhD student in Computer Science at Stanford
University, currently in my third year. I work at the intersection of Machine
Learning and Economics, and I am advised by [[Susan Athey
[https://athey.people.stanford.edu/]]

* Research Interests

I works at the intersection of Economics and Machine Learning, using methods
from each into the other. My focus areas are machine learning applied
to Economic structural modeling and Causal Inference, Recommendation Systems and
Experiment Design. I like to learn about/use Deep Learning
methods, Reinforcement Learning and Language Processing methods towards these
goals.

* Past Education
+ Graduation - B.Tech (Computer Science) with Honors and minor in Applied Statistics and Informatics, IIT Bombay, India
+ High School - Don Bosco School Park Circus, Kolkata, India

* Work experience
+ Researcher, IIM Calcutta
+ Software Engineer, Google (London)
+ Research Intern, Microsoft Research (Redmond) (Mobility and Networking Group)
+ Researcher, IST Austria (Vienna) (Advised by Krishnendu Chatterjee)
