#+author: Ayush Kanodia
#+title: The World Barista Championships are fun!
#+EMAIL: kanodiaayush@gmail.com
#+date:<2023-04-23 Sun>

Today i went down a bit of a rabbit hole. I enjoy watching James Hoffman's videos on coffee, and I started with wanting to understand James Hoffman's background, to see his education etc. It turns out he won the world barista championship (WBC) (yes, that exists), in 2007. The contest involves baristas making 3 drinks. A straight espresso shot, a cappucino, and one signature drink. I found his [[https://www.youtube.com/watch?v=6nshvMILgfU&ab_channel=PeterHua][winning performance]] online. It is a treat to watch. The performance is high quality, and the background music is nice. Then i looked in to the WBC, and it was started in 2000. Curious about my own country, I found that India has won a silver at it in 2002 actually, and [[https://www.kaapisolutions.com/about-ceo/][Vikram Khurrana]] who won it worked for coffee day at the time. India has hit the top 10 a few other times, and about 50 countries participate on average. The winner of national barista championships in each country is sent up. I also found the 2022 performance of india on video. The barista was from Nagpur, and his [[https://www.youtube.com/watch?v=XMBF3VwdpAI&t=605s&ab_channel=WorldCoffeeChampionships][presentation]] was very fun to watch. The signature drink our guy made was sensational, it was iced espresso, topped with Jasmine tea, frozen/distilled high cream milk, a fruit infusion, and finally, orange peel infusion to add a signature of Nagpur, his home town. It was inpiring when he described it, made me think of India as a potential world class coffee producing/drinking country.
