name: Publish Notion website to GitHub Pages

on:
  # Manual update only.
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: leoncvlt/loconotion
          path: loconotion
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: pages_repo
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Using Python 3.8 which is more compatible with older packages
      - name: Setup Chrome and Chromedriver
        uses: browser-actions/setup-chrome@v1
      - name: Install Loconotion dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install six==1.16.0 urllib3==1.25.9
          cd loconotion
          python -m pip install -r requirements.txt
          cd ..
      - name: Run Loconotion
        run: |
          which chrome
          which chromedriver
          cd loconotion
          # Run Loconotion from its root directory with the site.toml file
          python loconotion "../pages_repo/site.toml" --chromedriver $(which chromedriver) --verbose
          
          # Debug: Check what directories were created
          echo "Checking generated directories:"
          ls -la
          
          if [ -d "dist" ]; then
            echo "Content of dist directory:"
            ls -la dist/
          fi
          
          # Copy the dist directory to pages_repo for deployment
          if [ -d "dist" ]; then
            cp -r dist/* ../pages_repo/
            echo "Copied dist content to pages_repo directory"
          fi
          
          cd ..
          echo "Files in pages_repo directory:"
          ls -la pages_repo
      - name: Push to GitHub pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Debug: Check directories before running deploy.sh
          echo "Current directory: $(pwd)"
          ls -la
          
          # Using the correct path to the generated site
          GIT_DEPLOY_DIR=site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
